package org.springboot.blog.project.blogs.mapper;

import org.springboot.blog.project.blogs.entity.BlogText;

public interface BlogTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_TEXT
     *
     * @mbggenerated Thu May 23 11:26:23 CST 2019
     */
    int deleteByPrimaryKey(Long blogTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_TEXT
     *
     * @mbggenerated Thu May 23 11:26:23 CST 2019
     */
    int insert(BlogText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_TEXT
     *
     * @mbggenerated Thu May 23 11:26:23 CST 2019
     */
    int insertSelective(BlogText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_TEXT
     *
     * @mbggenerated Thu May 23 11:26:23 CST 2019
     */
    BlogText selectByPrimaryKey(Long blogTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_TEXT
     *
     * @mbggenerated Thu May 23 11:26:23 CST 2019
     */
    int updateByPrimaryKeySelective(BlogText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_TEXT
     *
     * @mbggenerated Thu May 23 11:26:23 CST 2019
     */
    int updateByPrimaryKey(BlogText record);
}