package org.springboot.blog.project.blogs.mapper;

import java.util.List;

import org.springboot.blog.project.blogs.bean.BlogBean;
import org.springboot.blog.project.blogs.dto.CommentReplyDto;
import org.springboot.blog.project.blogs.entity.Blog;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Tue Jul 02 17:22:36 CST 2019
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Tue Jul 02 17:22:36 CST 2019
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Tue Jul 02 17:22:36 CST 2019
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Tue Jul 02 17:22:36 CST 2019
     */
    Blog selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Tue Jul 02 17:22:36 CST 2019
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Tue Jul 02 17:22:36 CST 2019
     */
    int updateByPrimaryKey(Blog record);
    
    /**
     * 博客详情
     */
    List<BlogBean> qryBlogBaseInfo();
    
    /**
     * 总评论数
     */
    BlogBean qryBlogCommentSum(Long blogId);
    
    /**
     * 博客详情
     */
    BlogBean qryBlogDetail(Long blogId);
    
}