package org.springboot.blog.project.blogs.mapper;

import org.springboot.blog.project.blogs.entity.BlogCatalog;

public interface BlogCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_CATALOG
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    int deleteByPrimaryKey(Long blogCatalogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_CATALOG
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    int insert(BlogCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_CATALOG
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    int insertSelective(BlogCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_CATALOG
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    BlogCatalog selectByPrimaryKey(Long blogCatalogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_CATALOG
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    int updateByPrimaryKeySelective(BlogCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG_CATALOG
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    int updateByPrimaryKey(BlogCatalog record);
}