package org.springboot.blog.project.blogs.mapper;

import org.springboot.blog.project.blogs.entity.CommentReply;

public interface CommentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_REPLY
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    int deleteByPrimaryKey(Long replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_REPLY
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    int insert(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_REPLY
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    int insertSelective(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_REPLY
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    CommentReply selectByPrimaryKey(Long replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_REPLY
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    int updateByPrimaryKeySelective(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_REPLY
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    int updateByPrimaryKey(CommentReply record);
}