package org.springboot.blog.project.blogs.dto;

import java.util.Date;

public class CommentReplyDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT_REPLY.reply_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    private Long replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT_REPLY.reply_text
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    private String replyText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT_REPLY.parent_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT_REPLY.user_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT_REPLY.create_date
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT_REPLY.state
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    private Long state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT_REPLY.reply_id
     *
     * @return the value of COMMENT_REPLY.reply_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT_REPLY.reply_id
     *
     * @param replyId the value for COMMENT_REPLY.reply_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT_REPLY.reply_text
     *
     * @return the value of COMMENT_REPLY.reply_text
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public String getReplyText() {
        return replyText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT_REPLY.reply_text
     *
     * @param replyText the value for COMMENT_REPLY.reply_text
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public void setReplyText(String replyText) {
        this.replyText = replyText == null ? null : replyText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT_REPLY.parent_id
     *
     * @return the value of COMMENT_REPLY.parent_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT_REPLY.parent_id
     *
     * @param parentId the value for COMMENT_REPLY.parent_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT_REPLY.user_id
     *
     * @return the value of COMMENT_REPLY.user_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT_REPLY.user_id
     *
     * @param userId the value for COMMENT_REPLY.user_id
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT_REPLY.create_date
     *
     * @return the value of COMMENT_REPLY.create_date
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT_REPLY.create_date
     *
     * @param createDate the value for COMMENT_REPLY.create_date
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT_REPLY.state
     *
     * @return the value of COMMENT_REPLY.state
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT_REPLY.state
     *
     * @param state the value for COMMENT_REPLY.state
     *
     * @mbggenerated Thu May 23 11:22:41 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }
}