package org.springboot.blog.project.blogs.entity;

public class BlogCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_CATALOG.blog_catalog_id
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    private Long blogCatalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLOG_CATALOG.blog_catalog_info
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    private String blogCatalogInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_CATALOG.blog_catalog_id
     *
     * @return the value of BLOG_CATALOG.blog_catalog_id
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    public Long getBlogCatalogId() {
        return blogCatalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_CATALOG.blog_catalog_id
     *
     * @param blogCatalogId the value for BLOG_CATALOG.blog_catalog_id
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    public void setBlogCatalogId(Long blogCatalogId) {
        this.blogCatalogId = blogCatalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLOG_CATALOG.blog_catalog_info
     *
     * @return the value of BLOG_CATALOG.blog_catalog_info
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    public String getBlogCatalogInfo() {
        return blogCatalogInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLOG_CATALOG.blog_catalog_info
     *
     * @param blogCatalogInfo the value for BLOG_CATALOG.blog_catalog_info
     *
     * @mbggenerated Thu May 23 11:29:26 CST 2019
     */
    public void setBlogCatalogInfo(String blogCatalogInfo) {
        this.blogCatalogInfo = blogCatalogInfo == null ? null : blogCatalogInfo.trim();
    }
}