package org.springboot.blog.project.blogs.entity;

import java.util.Date;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.user_id
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.user_name
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.user_pwd
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.create_date
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.blog_num
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    private Long blogNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.state
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    private Long state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.user_id
     *
     * @return the value of USERINFO.user_id
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.user_id
     *
     * @param userId the value for USERINFO.user_id
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.user_name
     *
     * @return the value of USERINFO.user_name
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.user_name
     *
     * @param userName the value for USERINFO.user_name
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.user_pwd
     *
     * @return the value of USERINFO.user_pwd
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.user_pwd
     *
     * @param userPwd the value for USERINFO.user_pwd
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.create_date
     *
     * @return the value of USERINFO.create_date
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.create_date
     *
     * @param createDate the value for USERINFO.create_date
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.blog_num
     *
     * @return the value of USERINFO.blog_num
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public Long getBlogNum() {
        return blogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.blog_num
     *
     * @param blogNum the value for USERINFO.blog_num
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public void setBlogNum(Long blogNum) {
        this.blogNum = blogNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.state
     *
     * @return the value of USERINFO.state
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.state
     *
     * @param state the value for USERINFO.state
     *
     * @mbggenerated Wed May 22 20:54:11 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }
}